export const LOGIN = "LOGIN";
export const ERROR = "ERROR";
export const LOGOUT = "LOGOUT";
// export const ONLOGOUT = "ONLOGOUT";
export const PROFILE = "PROFILE";
export const ONPROFILE = "ONPROFILE";
export const ONCLUB = "ONCLUB";
export const ONTEST = "ONTEST";
export const RESTORE_TOKEN = "RESTORE_TOKEN";
export const PRO = "PRO";
export const FORPASSWORD = "FORPASSWORD";
export const    RESET = "RESET";
export const    ONCLUBS = "ONCLUBS";
export const UPDATE = "UPDATE";
export const onEvents="onEvents";
export const onCompetitions="onCompetitions";
export const onAffiliate="onAffiliate";
export const onToggleSaveAffiliate="onToggleSaveAffiliate";
export const onEventByTowns = "onEventByTowns";
export const onUpdateImage = "onUpdateImage";
export const onCheckInAffiliate = "onCheckInAffiliate";
export const LOADTOKEN = "LOADTOKEN";
export const onEventsByClubs = "onEventsByClubs";
export const clearClubType = "CLEARCLUB" 
export const clearEventsType = "clearEventsByTowns"
export const clearEventsByClubType = "clearEventsbyClub"
export const clearOnProfileType = "clearOnProfile"
export const onFavProfileType = "onFavProfile"
export const clearFavProfileType = "clearFavProfile"

